image:
  file: .gitpod.Dockerfile
tasks:
  - name: frontend
    init: cd frontend && npm install && npm run dev
  - name: server
    init: cd server && vr watch
    openMode: split-right
ports:
  - port: 8000
    onOpen: ignore
  - port: 4000
    onOpen: ignore
vscode:
  extensions:
    - "voorjaar.windicss-intellisense"
    - "k--kato.intellij-idea-keybindings"
    - "svelte.svelte-vscode"
    - "github.vscode-pull-request-github"
    - "denoland.vscode-deno"
    - "akamud.vscode-theme-onedark"